package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

const sleepScript = `#!/bin/bash
# Auto-generated by bt-sleepd
PATH=%s:%s
{
  echo "[$(date)] sleep triggered"
  %s --sleep
  echo "[$(date)] exit=$?"
} >> /tmp/bt-sleepd.log 2>&1
`

const wakeScript = `#!/bin/bash
# Auto-generated by bt-sleepd
PATH=%s:%s
{
  echo "[$(date)] wakeup triggered"
  %s --wake
  echo "[$(date)] bluetooth re-enabled"
} >> /tmp/bt-sleepd.log 2>&1
`

// doInstall creates ~/.sleep and ~/.wakeup scripts that invoke bt-sleepd.
func doInstall(log *Logger, binaryPath string) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("home dir: %w", err)
	}

	btPath, err := exec.LookPath("blueutil")
	if err != nil {
		return fmt.Errorf("blueutil not found in PATH; install with `brew install blueutil`: %w", err)
	}
	btDir := filepath.Dir(btPath)

	binDir := filepath.Dir(binaryPath)
	pathPrefix := btDir + ":" + binDir

	sleepContent := fmt.Sprintf(sleepScript, pathPrefix, "/usr/bin:/bin", binaryPath)
	sleepPath := filepath.Join(home, ".sleep")
	if err := os.WriteFile(sleepPath, []byte(sleepContent), 0o755); err != nil {
		return fmt.Errorf("writing %s: %w", sleepPath, err)
	}
	log.Info("Created %s", sleepPath)

	wakeContent := fmt.Sprintf(wakeScript, btDir, "/usr/bin:/bin", binaryPath)
	wakePath := filepath.Join(home, ".wakeup")
	if err := os.WriteFile(wakePath, []byte(wakeContent), 0o755); err != nil {
		return fmt.Errorf("writing %s: %w", wakePath, err)
	}
	log.Info("Created %s", wakePath)

	fmt.Println()
	fmt.Println("✅ Installed! Start sleepwatcher if not already running:")
	fmt.Println()
	fmt.Println("   brew services start sleepwatcher")
	fmt.Println()
	fmt.Println("Or restart it to pick up changes:")
	fmt.Println()
	fmt.Println("   brew services restart sleepwatcher")
	return nil
}

// doUninstall removes ~/.sleep and ~/.wakeup scripts.
func doUninstall(log *Logger) error {
	home, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("home dir: %w", err)
	}

	removed := false
	for _, name := range []string{".sleep", ".wakeup"} {
		path := filepath.Join(home, name)
		if _, err := os.Stat(path); err == nil {
			if err := os.Remove(path); err != nil {
				log.Error("failed to remove %s: %v", path, err)
			} else {
				log.Info("Removed %s", path)
				removed = true
			}
		}
	}
	if !removed {
		log.Info("No scripts found to remove (~/.sleep, ~/.wakeup).")
	}
	fmt.Println()
	fmt.Println("Done. Stop sleepwatcher if you no longer need it:")
	fmt.Println()
	fmt.Println("   brew services stop sleepwatcher")
	return nil
}
